"""Regenerate .wiki/wiki/index.md from frontmatter + first blockquote of every wiki page.

Walks `.wiki/wiki/**/*.md`, parses the YAML-ish frontmatter, grabs the first `> ...`
line as a one-liner, and writes a grouped index. Run after adding/editing wiki pages.
"""

from __future__ import annotations

from pathlib import Path
import re

REPO_ROOT = Path(__file__).resolve().parent.parent
WIKI_DIR = REPO_ROOT / ".wiki" / "wiki"
INDEX = WIKI_DIR / "index.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
ONELINER_RE = re.compile(r"^> (.+)$", re.MULTILINE)


def parse_page(path: Path) -> dict[str, str]:
    text = path.read_text()
    fm: dict[str, str] = {}
    m = FRONTMATTER_RE.match(text)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip()
    one = ""
    mo = ONELINER_RE.search(text)
    if mo:
        one = mo.group(1).strip()
    return {"title": path.stem, "path": str(path.relative_to(WIKI_DIR)), "oneliner": one, **fm}


def main() -> None:
    by_kind: dict[str, list[dict]] = {
        "games": [],
        "game_types": [],
        "strategies/frame_only": [],
        "strategies/brittle": [],
        "dispatch": [],
    }
    for path in sorted(WIKI_DIR.rglob("*.md")):
        rel = path.relative_to(WIKI_DIR)
        if rel.name == "index.md":
            continue
        page = parse_page(path)
        top = rel.parts[0]
        if top == "games":
            by_kind["games"].append(page)
        elif top == "game_types":
            by_kind["game_types"].append(page)
        elif top == "strategies" and len(rel.parts) >= 2:
            sub = rel.parts[1]
            key = f"strategies/{sub}"
            by_kind.setdefault(key, []).append(page)
        else:
            by_kind["dispatch"].append(page)

    lines: list[str] = [
        "# Wiki Index",
        "",
        "Auto-generated by `scripts/generate_wiki_index.py`. Regenerate after editing any wiki page.",
        "",
    ]

    def section(header: str, items: list[dict]) -> None:
        lines.append(f"## {header} ({len(items)})")
        lines.append("")
        for item in sorted(items, key=lambda x: x["title"]):
            status = ""
            if "status_v1" in item:
                status = f" — v1 {item['status_v1']}"
                if "status_v2" in item and "n/a" not in item["status_v2"]:
                    status += f", v2 {item['status_v2']}"
            one = item["oneliner"] or "(no description)"
            lines.append(f"- [[{item['path']}]]{status} — {one}")
        lines.append("")

    section("Games", by_kind["games"])
    section("Game Types", by_kind["game_types"])
    section("Strategies — Frame-only (generalizable)", by_kind.get("strategies/frame_only", []))
    section("Strategies — Brittle (refactor targets)", by_kind.get("strategies/brittle", []))
    section("Dispatch / Misc", by_kind["dispatch"])

    lines.append("## Raw sources")
    lines.append("")
    raw_dir = WIKI_DIR.parent / "raw"
    if raw_dir.exists():
        for p in sorted(raw_dir.rglob("*.md")):
            rel = p.relative_to(WIKI_DIR.parent)
            lines.append(f"- [[../{rel}]]")
        lines.append("")

    INDEX.write_text("\n".join(lines))
    total = sum(len(v) for v in by_kind.values())
    print(f"Wrote {INDEX} with {total} pages indexed.")


if __name__ == "__main__":
    main()
