"""Regenerate `.wiki/wiki/index.md` from frontmatter + first blockquote.

Walks `.wiki/wiki/**/*.md`, parses YAML-ish frontmatter, grabs a
one-liner from (1) the first ``> ...`` blockquote when present, else
(2) the frontmatter `description`, (3) `purpose`, or (4) `type` field.
Groups pages by their top-level subdirectory (concepts / lessons /
debug / reasoning / games / game_types / strategies / llm_context /
top-level dispatch like architecture, selector, log) so the LLM
reading the index can drill into the right category fast.

Per Karpathy LLM-Wiki §7.1: index.md is the LLM's first stop. The
LLM reads it, picks the relevant category, then reads specific
pages. R23b — generator upgrade so the index meaningfully helps
that workflow rather than dumping 30 dispatch entries into one
list.

Run after adding / editing wiki pages.
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WIKI_DIR = REPO_ROOT / ".wiki" / "wiki"
INDEX = WIKI_DIR / "index.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
ONELINER_RE = re.compile(r"^> (.+)$", re.MULTILINE)

CATEGORY_ORDER = [
    "games",
    "game_types",
    "strategies/frame_only",
    "strategies/brittle",
    "concepts",
    "lessons",
    "debug",
    "reasoning",
    "llm_context",
    "top_level",
]

CATEGORY_LABELS = {
    "games": "Games",
    "game_types": "Game Types",
    "strategies/frame_only": "Strategies — Frame-only (generalizable)",
    "strategies/brittle": "Strategies — Brittle (refactor targets)",
    "concepts": "Concepts (cross-game domain entities)",
    "lessons": "Lessons (engineering wisdom from past incidents)",
    "debug": "Debug (failure-mode playbooks)",
    "reasoning": "Reasoning (observation→hypothesis→action chains)",
    "llm_context": "LLM Context (compact docs read first by Qwen)",
    "top_level": "Top-level dispatch (architecture, selector, log, schema)",
}


def parse_page(path: Path) -> dict[str, str]:
    text = path.read_text()
    fm: dict[str, str] = {}
    m = FRONTMATTER_RE.match(text)
    if m:
        for line in m.group(1).splitlines():
            if ":" in line:
                k, v = line.split(":", 1)
                fm[k.strip()] = v.strip()
    one = ""
    mo = ONELINER_RE.search(text)
    if mo:
        one = mo.group(1).strip()
    if not one:
        for fallback_key in ("description", "purpose", "type"):
            v = fm.get(fallback_key, "")
            if v:
                one = v
                break
    return {"title": path.stem, "path": str(path.relative_to(WIKI_DIR)), "oneliner": one, **fm}


def categorize(rel: Path) -> str:
    parts = rel.parts
    if parts[0] == "strategies" and len(parts) >= 2:
        return f"strategies/{parts[1]}"
    if parts[0] in ("games", "game_types", "concepts", "lessons", "debug", "reasoning", "llm_context"):
        return parts[0]
    return "top_level"


def main() -> None:
    by_cat: dict[str, list[dict]] = {key: [] for key in CATEGORY_ORDER}
    for path in sorted(WIKI_DIR.rglob("*.md")):
        rel = path.relative_to(WIKI_DIR)
        if rel.name == "index.md":
            continue
        cat = categorize(rel)
        by_cat.setdefault(cat, []).append(parse_page(path))

    lines: list[str] = [
        "# Wiki Index",
        "",
        "Auto-generated by `scripts/generate_wiki_index.py`. Regenerate after editing any wiki page.",
        "",
        "Per Karpathy LLM-Wiki §7.1, this is the LLM's first stop — it skims",
        "the catalog, picks the right category, and drills into specific",
        "pages from there.",
        "",
        f"**Total pages**: {sum(len(v) for v in by_cat.values())}.",
        "",
    ]

    def page_line(item: dict) -> str:
        status = ""
        if "status_v1" in item:
            status = f" — v1 {item['status_v1']}"
            if "status_v2" in item and "n/a" not in item["status_v2"]:
                status += f", v2 {item['status_v2']}"
        elif "status_v1_brittle" in item:
            status = f" — v1 brittle {item['status_v1_brittle']}"
            generic = item.get("status_v1_generic", "")
            if generic:
                status += f", generic {generic}"
        one = item["oneliner"] or "(no description)"
        return f"- [[{item['path']}]]{status} — {one}"

    def section(cat: str, items: list[dict]) -> None:
        if not items:
            return
        label = CATEGORY_LABELS.get(cat, cat)
        lines.append(f"## {label} ({len(items)})")
        lines.append("")
        for item in sorted(items, key=lambda x: x["title"]):
            lines.append(page_line(item))
        lines.append("")

    for cat in CATEGORY_ORDER:
        section(cat, by_cat[cat])

    raw_dir = WIKI_DIR.parent / "raw"
    if raw_dir.exists():
        raw_pages = sorted(raw_dir.rglob("*.md"))
        if raw_pages:
            lines.append("## Raw sources")
            lines.append("")
            for p in raw_pages:
                rel = p.relative_to(WIKI_DIR.parent)
                lines.append(f"- [[../{rel}]]")
            lines.append("")

    INDEX.write_text("\n".join(lines))
    total = sum(len(v) for v in by_cat.values())
    print(f"Wrote {INDEX} with {total} pages indexed across {sum(1 for v in by_cat.values() if v)} categories.")


if __name__ == "__main__":
    main()
